# Generated by Django 3.0.1 on 2020-02-01 00:12

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20200131_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(base_url='media/avatars/'), upload_to='media/'),
        ),
    ]
